"""Modular modCAM16-HK radial palette generator."""

from .aces_jmh import (
    REC709_D65_PRIMARIES_XY,
    REC2020_D65_PRIMARIES_XY,
    ACESJMhParams,
    init_jmh_params,
    jmh_to_cartesian,
    output_j_from_xyz,
    params_for_profile,
    xyz_to_aces_j,
)
from .cam16_hk import AppearanceModel
from .cli import generate_release
from .colorchecker import (
    COLORCHECKER_ASSIGNMENT_POLICY,
    COMPENSATED_COLORCHECKER_ASSIGNMENT_POLICY,
    COMPENSATED_COLORCHECKER_MATCHING_MODE,
    DIRECT_COLORCHECKER_DISTANCE_METRIC,
    DIRECT_COLORCHECKER_MATCHING_MODE,
    build_colorchecker_marker_assignments,
    build_compensated_colorchecker_marker_assignments,
    build_direct_colorchecker_marker_assignments,
)
from .colorimetry import GAMUT_MATRICES
from .config import (
    COMPENSATION_PROFILE_CHOICES,
    COMPENSATION_PROFILE_DEFINITIONS,
    COMPENSATION_PROFILE_NAMES,
    COMPENSATION_PROFILES,
    DEFAULT_COMPENSATION_P3_CHROMA_COMPANDING_K,
    DEFAULT_COMPENSATION_SRGB_CHROMA_COMPANDING_K,
    PUBLISHED_CENTER_ACESCG,
    CompensationConfig,
    CompensationProfile,
    CompensationProfileConfig,
    Config,
    default_config,
    load_config,
)
from .fitting import (
    CompensationFitDiagnostics,
    CompensationFitResult,
    evaluate_aces_j_objective,
    evaluate_anchor_objective,
    fit_compensation_anchor,
    fit_profile,
    fit_profile_anchor,
    unique_palette_colors,
)
from .ocio_compensation import (
    CompensationDiagnostics,
    CompensationProcessor,
    TargetGamutProjection,
    apply_inverse_view_compensation,
    compensate_candidate_colors,
    compensate_foreground,
    load_compensation_processor,
    load_ocio_processors,
    project_target_to_limiting_gamut,
    solve_neutral_y,
    solve_profile_neutral_y,
    solve_source_neutral_y,
)
from .palette import PaletteResult, build_palette
from .render import (
    RenderedPalette,
    render_palette_layers,
    render_radial_palette_with_masks,
)

__all__ = [
    "COLORCHECKER_ASSIGNMENT_POLICY",
    "COMPENSATED_COLORCHECKER_ASSIGNMENT_POLICY",
    "COMPENSATED_COLORCHECKER_MATCHING_MODE",
    "COMPENSATION_PROFILES",
    "COMPENSATION_PROFILE_CHOICES",
    "COMPENSATION_PROFILE_DEFINITIONS",
    "COMPENSATION_PROFILE_NAMES",
    "DEFAULT_COMPENSATION_P3_CHROMA_COMPANDING_K",
    "DEFAULT_COMPENSATION_SRGB_CHROMA_COMPANDING_K",
    "DIRECT_COLORCHECKER_DISTANCE_METRIC",
    "DIRECT_COLORCHECKER_MATCHING_MODE",
    "GAMUT_MATRICES",
    "PUBLISHED_CENTER_ACESCG",
    "REC709_D65_PRIMARIES_XY",
    "REC2020_D65_PRIMARIES_XY",
    "ACESJMhParams",
    "AppearanceModel",
    "CompensationConfig",
    "CompensationDiagnostics",
    "CompensationFitDiagnostics",
    "CompensationFitResult",
    "CompensationProcessor",
    "CompensationProfile",
    "CompensationProfileConfig",
    "Config",
    "PaletteResult",
    "RenderedPalette",
    "TargetGamutProjection",
    "apply_inverse_view_compensation",
    "build_colorchecker_marker_assignments",
    "build_compensated_colorchecker_marker_assignments",
    "build_direct_colorchecker_marker_assignments",
    "build_palette",
    "compensate_candidate_colors",
    "compensate_foreground",
    "default_config",
    "evaluate_aces_j_objective",
    "evaluate_anchor_objective",
    "fit_compensation_anchor",
    "fit_profile",
    "fit_profile_anchor",
    "generate_release",
    "init_jmh_params",
    "jmh_to_cartesian",
    "load_compensation_processor",
    "load_config",
    "load_ocio_processors",
    "output_j_from_xyz",
    "params_for_profile",
    "project_target_to_limiting_gamut",
    "render_palette_layers",
    "render_radial_palette_with_masks",
    "solve_neutral_y",
    "solve_profile_neutral_y",
    "solve_source_neutral_y",
    "unique_palette_colors",
    "xyz_to_aces_j",
]
